import{S as p,a as h,i as a}from"./assets/vendor-DhpBV7YY.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const L=new p(".gallery a",{captionsData:"alt",captionDelay:250}),i=document.querySelector(".loader");function _(t){const r=document.querySelector(".gallery"),s=t.map(n=>`
    <li class="gallery__item">
      <a class="gallery__link" href="${n.largeImageURL}">
        <img class="gallery__image" src="${n.webformatURL}" alt="${n.tags}" />
      </a>
      <div class="image__info">
        <p><strong>Likes:</strong> ${n.likes}</p>
        <p><strong>Views:</strong> ${n.views}</p>
        <p><strong>Comments:</strong> ${n.comments}</p>
        <p><strong>Downloads:</strong> ${n.downloads}</p>
      </div>
    </li>
  `).join("");r.insertAdjacentHTML("beforeend",s),L.refresh()}function w(){const t=document.querySelector(".gallery");t.innerHTML=""}function u(){i&&i.classList.remove("hidden")}function b(){i&&i.classList.add("hidden")}function S(){document.querySelector(".load__button").classList.remove("hidden")}function f(){document.querySelector(".load__button").classList.add("hidden")}const q="51218817-9c6b1fab233f845d5e532ac94",v="https://pixabay.com/api/",P=15;async function E(t,r=1){return(await h.get(v,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:P}})).data}const m=document.querySelector(".form"),$=m.elements["search-text"],A=document.querySelector(".load__button");let y="",c=1,d=0;m.addEventListener("submit",async t=>{t.preventDefault();const r=$.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search term!"});return}y=r,c=1,u(),f(),w(),await g()});A.addEventListener("click",async()=>{c++,await g()});async function g(){try{u();const t=await E(y,c);if(d=t.totalHits,t.hits.length===0){hideLoadBtn(),a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}_(t.hits),document.querySelectorAll(".gallery__item").length>=d?(f(),a.info({title:"The End",message:"We`re sorry, but you`ve reached the end of search results."})):S()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{b()}}
//# sourceMappingURL=index.js.map
