import{S as h,a as p,i as a}from"./assets/vendor-DhpBV7YY.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const L=new h(".gallery a",{captionsData:"alt",captionDelay:250}),i=document.querySelector(".loader");function _(e){const r=document.querySelector(".gallery"),s=e.map(n=>`
    <li class="gallery__item">
      <a class="gallery__link" href="${n.largeImageURL}">
        <img class="gallery__image" src="${n.webformatURL}" alt="${n.tags}" />
      </a>
      <div class="image__info">
        <p><strong>Likes:</strong> ${n.likes}</p>
        <p><strong>Views:</strong> ${n.views}</p>
        <p><strong>Comments:</strong> ${n.comments}</p>
        <p><strong>Downloads:</strong> ${n.downloads}</p>
      </div>
    </li>
  `).join("");r.insertAdjacentHTML("beforeend",s),L.refresh()}function w(){const e=document.querySelector(".gallery");e.innerHTML=""}function f(){i&&i.classList.remove("hidden")}function b(){i&&i.classList.add("hidden")}function S(){document.querySelector(".load__button").classList.remove("hidden")}function d(){document.querySelector(".load__button").classList.add("hidden")}const q="51218817-9c6b1fab233f845d5e532ac94",v="https://pixabay.com/api/",P=15;async function E(e,r=1){return(await p.get(v,{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:P}})).data}const g=document.querySelector(".form"),B=g.elements["search-text"],$=document.querySelector(".load__button");let m="",l=1,u=0;g.addEventListener("submit",async e=>{e.preventDefault();const r=B.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search term!"});return}m=r,l=1,f(),d(),w(),await y()});$.addEventListener("click",async()=>{l++,await y()});async function y(){try{f();const e=await E(m,l);if(u=e.totalHits,e.hits.length===0){d(),a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}_(e.hits),document.querySelectorAll(".gallery__item").length>=u?(d(),a.info({title:"The End",message:"We`re sorry, but you`ve reached the end of search results."})):S(),l>1&&A()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{b()}}function A(){const{height:e}=document.querySelector(".gallery__item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
